steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        key: "SERVICE"
        options:
          - label: "Blueprint service"
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - wait
  
  - label: "testing service name in sh file"
    key: "blueprints"
    command: echo "blueprint command"
    if: (key:SERVICE == blueprints)
