env:
  PIPELINE_SCRIPT: C:\\buildkite-agent\\builds\\RTC-DLLA48-1\\rtctek\\test-deploy\\.buildkite\\pipeline.sh

steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        key: "SERVICE"
        multiple: true
        options:
          - label: "Blueprint service "
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - label: "testing service name in yml"
    command: |
      SERVICES=$(buildkite-agent meta-data get SERVICE)
      echo "Services are: $SERVICES"
      for SERVICE in $SERVICES; do
      echo "Fetching details for service: $SERVICE"
      done

  - label: "testing service name in sh file"
    command: bash $PIPELINE_SCRIPT
