steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        key: "SERVICE"
        options:
          - label: "Blueprint service"
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - wait

  - label: "testing blueprint service"
    command: |
      if [[ "$$(buildkite-agent meta-data get SERVICE)" == "blueprints" ]]; then
        echo "blueprint service testing"
      fi
  
  - label: "Testing authn2 service"
    command: echo "authn2 command"
    # if: buildkite:env:SERVICE == "authn2"
