steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        key: "SERVICE"
        options:
          - label: "Blueprint service"
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - wait

  - label: "testing blueprint service"
    key: "blueprints"
    command: echo "blueprint command"
    if: buildkite:env:SERVICE == "blueprints"
  
  - label: "Testing authn2 service"
    command: echo "authn2 command"
    if: buildkite:env:SERVICE == "authn2"
