steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        multiple: "true"
        key: "SERVICE"
        options:
          - label: "Blueprint service"
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - wait

  - label: ":pipeline: Upload and run testing.yml"
    command: |
      echo "RELEASE_TYPE=${SERVICE}" > service.env
      buildkite-agent pipeline upload testing.yml
    env:
      SERVICE: "${SERVICE}" 

