steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        key: "SERVICE"
        multiple: true
        options:
          - label: "Blueprint service"
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - label: "testing service name in sh file"
    command: |
      if [[ "${SERVICE[@]}" =~ "blueprints" ]]; then
        bash $PIPELINE_SCRIPT
        echo "Service name is 'blueprints'"
      else
        echo "Skipping step as 'blueprints' service is not selected"
      fi
