steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        key: "SERVICE"
        multiple: true
        options:
          - label: "Blueprint service"
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"
  - wait
  - label: "testing service name in sh file"
    command: echo "test"; buildkite-agent meta-data get SERVICE
