env:
  SETUP_SCRIPT: C:\\buildkite-agent\\builds\\RTC-DLLA48-1\\rtctek\\test-deploy\\.buildkite\\setup.sh
  PIPELINE_SCRIPT: C:\\buildkite-agent\\builds\\RTC-DLLA48-1\\rtctek\\test-deploy\\.buildkite\\pipeline.sh

steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        multiple: "true"
        key: "SERVICE"
        options:
          - label: "Blueprint service"
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - label: "Execute Commands for Selected Service"
    command: 
      - $SETUP_SCRIPT "$(buildkite-agent meta-data get SERVICE)"
      - echo "next step"
