env:
  PIPELINE_SCRIPT: C:\\buildkite-agent\\builds\\RTC-DLLA48-1\\rtctek\\test-deploy\\.buildkite\\pipeline.sh

steps:
  - block: "Run Config"
    fields:
      - select: "Services"
        key: "SERVICE"
        multiple: true
        options:
          - label: "Blueprint service "
            value: "blueprints"
          - label: "Authn2 service"
            value: "authn2"

  - label: "testing service"
    commands: 
      - echo "service are $BUILDKITE_PLUGIN_INPUT_SERVICE"
