version: '5'
description: 'Example pipeline'

inputs:
  - id: "selected_services"
    description: "Choose services (comma-separated)"
    required: true
    schema:
      type: string

env:
  SERVICES_LIST: ""

steps:
  - label: "Process Selected Services"
    command: |
      #!/bin/bash
      IFS=', ' read -ra SERVICES <<< "$(buildkite-agent meta-data get selected_services)"
      
      # Convert the array to a space-separated string for easier handling
      SERVICES_LIST=$(IFS=' '; echo "${SERVICES[*]}")
      
      echo "Selected services: $SERVICES_LIST"
      export SERVICES_LIST
      
  - label: "Use Processed Services"
    command: |
      #!/bin/bash
      echo "Processing services: $SERVICES_LIST"
      # Example processing here
