steps:
  - command: |
      echo "blueprint servicews"
    label: ":hammer: Run Tests"
    if: build.env('SERVICES') =~ /^blue\//


  - command: |
      buildkite-agent meta-data get SERVICE
      echo "running for authn2"
    label: ":hammer: Run Tests"
    if: build.env('SERVICES') != 'authn2'
