steps:
  - command: |
      buildkite-agent meta-data get SERVICE
    label: ":hammer: Run Tests"
    if: SERVICE == "blueprints"

  - command: |
      buildkite-agent meta-data get SERVICE
      echo "running for authn2"
    label: ":hammer: Run Tests"
    if: SERVICE == "authn2"
