steps:
  - command: |
      buildkite-agent meta-data get SERVICE > SERVICES
    label: ":hammer: Run Tests"
    if: SERVICES == "blueprints"

  - command: |
      buildkite-agent meta-data get SERVICE
      echo "running for authn2"
    label: ":hammer: Run Tests"
    if: SERVICES == "authn2"
